input: touchscreen: nt36xxx: fix snprintf warning
Fixes the following clang warning:

../drivers/input/touchscreen/nt36xxx/nt36xxx_mp_ctrlram.c:1293:3: error: 'snprintf' size argument is too large; destination buffer has size 32, $
                snprintf(mpcriteria, PAGE_SIZE, "novatek-mp-criteria-%04X", ts->nvt_pid);
                ^
1 error generated.

Change-Id: Ieb3331a226cb6e183aaac2f22e7e8dccf27af7fc
Signed-off-by: Khusika Dhamar Gusti <mail@khusika.com>

Conflicts:
	drivers/input/touchscreen/nt36xxx/nt36xxx_mp_ctrlram.c

Use on nt36672c driver for x3pro

Signed-off-by: Pierre2324 <pdbbasketball@gmail.com>